name: Client Deploy

on:
    push:
        branches:
            - main

defaults:
    run:
        working-directory: ./client

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code.
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build
              env:
                  CI: ""
                  REACT_APP_WS_URL: ${{ secrets.WS_URL }}

            - name: Deploy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
                  AWS_EC2_METADATA_DISABLED: true
              run: |
                  aws s3 sync \
                    --region ap-northeast-2 \
                    build s3://chatssu \
                    --delete
